### ISSUE TITLE
正文开始页眉不出现

### ISSUE THREAD

**Issue by carlprilo** [Jarvis-K/ECNU_Latex_Template#4]
按照模版，论文除封面、目录部分，应有“华东师范大学本科毕业论文”和论文标题的页眉，分别左右对齐，现有模版仅中英文摘要页显示页眉。

**Comment by carlprilo** [comment]
在SectionA.tex 首加入
\rhead{\TitleCHS}
\lhead{华东师范大学本科毕业论文} 
可以解决。

**Comment by Jarvis-K** [comment]
模版正文页眉也是没有文字的

**Comment by carlprilo** [comment]
2019.1.7教务公邮中发的毕业论文模版页眉包含汉字，原仓库中的模版的确没有。
